# Generated by Django 3.1.7 on 2021-04-30 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='An_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category_of_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work_supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Work_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='To_observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('technical_activities', models.CharField(max_length=200, null=True)),
                ('place_name_work', models.CharField(max_length=200, null=True)),
                ('started_work', models.DateField()),
                ('work_done', models.DateField()),
                ('person_give_naryad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
                ('team_members', models.ManyToManyField(to='enaryad.Team_members')),
                ('work_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.work_supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_work_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Entrusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_h_at_work', models.BigIntegerField(null=True)),
                ('holiday_h', models.BigIntegerField(null=True)),
                ('sick_h', models.BigIntegerField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='create_e_naryad_table_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_preparedness_time', models.DateField()),
                ('start_work', models.DateField()),
                ('finish_work', models.DateField()),
                ('workplace_preparation_text1', models.TextField()),
                ('workplace_preparation_text2', models.TextField()),
                ('workplace_preparation_text3', models.TextField()),
                ('admitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.admitting')),
                ('an_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.an_object')),
                ('category_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.category_of_work')),
                ('entrusted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.entrusted')),
                ('manufacturer_work_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.manufacturer_work_manager')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.organization')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.plot')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.subdivision')),
                ('team_members', models.ManyToManyField(to='enaryad.Team_members')),
                ('to_observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.to_observer')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
                ('work_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.work_manager')),
            ],
        ),
        migrations.AddField(
            model_name='admitting',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee'),
        ),
    ]
