# Generated by Django 3.1.7 on 2021-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enaryad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='To_observer',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='An_object',
            new_name='Object',
        ),
        migrations.RenameModel(
            old_name='Manufacturer_work_manager',
            new_name='Observer',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text1',
            new_name='disconnected_where',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='employee_preparedness_time',
            new_name='emergency_preparedness_time',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='username',
            new_name='enar_give',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='to_observer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text2',
            new_name='name_electrical',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='an_object',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='manufacturer_work_manager',
            new_name='observer',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text3',
            new_name='separate_instructions',
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='single_line_diagram',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Employee_Time',
        ),
    ]
