# Generated by Django 3.1.7 on 2021-05-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enaryad', '0002_auto_20210524_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Biot_engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.employee')),
            ],
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='biot_engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.biot_engineer'),
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='deputy_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enaryad.deputy_head'),
        ),
    ]
