# Generated by Django 3.1.7 on 2021-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enaryad', '0006_auto_20210616_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_e_naryad_table_1',
            name='organization',
            field=models.ManyToManyField(null=True, to='enaryad.Organization'),
        ),
    ]
